# Niconico Live Alert Plugin 1.5.0
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2012-2013

# Target community.  ex) community: [co1295679, co9999999, co11111111]
community: []

# Target user.       ex) user: [80190, 99999999, 111111111]
user: []

# Message templates.
messageTemplate: '&cNiconico live program has started!!&r'
messageTemplate2: '&cCommunity: [$com]&r'
messageTemplate3: '&cTitle: [$title]&r'
messageTemplate4: ''
messageTemplate5: ''

# URL message color code.
urlColor: '&d'

# Community nicknames.
communityNicknames:

# User nicknames.
userNicknames:

# Title keyword filters.
titleKeywords: []
