# Niconico Live Alert Plugin 1.3.0
# @author     ucchy
# @license    GPLv2
# @copyright  Copyright ucchy 2012


# アラート対象にするコミュニティ。
# 例) community: [co1295679, co9999999, co11111111]
community: []

# アラート対象にするユーザー。
# 例) user: [80190, 99999999, 111111111]
user: []

# 通知時のメッセージのテンプレート。
# $com はコミュニティ名(ニックネームがある場合は、ニックネーム)で、
# $user はユーザーID(ニックネームがある場合は、ニックネーム)で、
# $title は放送タイトルで、置き換えられます。
# &? はカラーコードに置き換えられます。
# 詳細はトピックをご参照ください。
# http://forum.minecraftuser.jp/viewtopic.php?f=38&t=7768
messageTemplate: '&cニコ生 [$com]で[$title]が開始しました！&r'
messageTemplate2: ''
messageTemplate3: ''
messageTemplate4: ''
messageTemplate5: ''

# URLメッセージのカラーコード。
# 詳細はトピックをご参照ください。
urlColor: '&d'

# コミュニティのニックネーム設定。
communityNicknames: 
  'co1295679' : '俺のやる気無しコミュ'

# ユーザーのニックネーム設定。
userNicknames:
  '80190' : 'うっちぃ'
