name: ${project.name}
main: com.github.ucchyocean.nicolivealert.NicoLiveAlertPlugin
version: ${project.version}
author: ucchy
description: ${project.description}
commands:
  nicolivealert:
    description: Niconico live alert plugin maintenance command.
    aliases: nla
    usage: /<command> disconnect|connect|reload
    permission: nicolivealert
    permission-message: You don't have permission <permission>
permissions:
  nicolivealert:
    description:  Niconico live alert plugin maintenance command.
    default: op
