name: ${project.name}
main: com.github.ucchyocean.nicolivealert.NicoLiveAlertPlugin
version: ${project.version}
author: ucchy
description: ${project.description}

commands:
  nicolivealert:
    description: Nico Live Alert plugin command.
    aliases: nla
    usage: /<command> [list|disconnect|connect|reload]
    permission: nicolivealert.command
    permission-message: You don't have permission <permission>

permissions:
  nicolivealert.command:
    description: Command permission.
    default: true
  nicolivealert.admin:
    description: Administration Commands permission.
    default: op
  nicolivealert.*:
    description: All Permissions of NicoLiveAlert plugin.
    children:
      nicolivealert.command: true
      nicolivealert.admin: true
