name: NicoLiveAlert
main: com.github.ucchyocean.nicolivealert.NicoLiveAlertPlugin
version: 0.1.0
authors: [ucchy]
load: startup
description: Niconico Live Alert Plugin.
commands:
  nicolivealert:
    description: Niconico live alert plugin maintenance command.
    aliases: nla
    usage: /<command> pause|start|reload
    permission: nicolivealert
    permission-message: You don't have permission <permission>
permissions:
  nicolivealert:
    description:  Niconico live alert plugin maintenance command.
